- build.gradle
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseDetails.java
This PR adds the JSON format to `created_date` and `last_modified` for CaseDetails.
> ROC-2760: add local date time format

- build.gradle
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
This PR adds clients to start and save an event, which will be used to update an existing case.
> ROC-3027: Add clients to send update events

- build.gradle
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataClientAutoConfiguration.java
https://tools.hmcts.net/jira/browse/ROC-3536
Updating to Spring Boot 2 / Spring Framework 5.
> ROC-3636: Update to Spring Boot 2 / Spring Framework 5

- build.gradle
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/PaginatedSearchMetadata.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/StartEventResponse.java
Allow unknown properties to allow for api extension
> Make API consistent and allow unknown properties

- README.md
> Add badges for README

- build.gradle
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataConfiguration.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/SearchCriteria.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/SearchResult.java
Jira: 
https://tools.hmcts.net/jira/browse/ROC-5098
> ROC-5098: Use elastic search for get cases

- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseDetails.java
- Allow copies to be created to promote immutability in its usage.
> Allow copys to be created

- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/BaseTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/User.java
https://tools.hmcts.net/jira/browse/RPE-1005
Add coverage to CaseAccessApi
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```
> RPE-1005 Add CaseAccessApi functional test

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/BaseTest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseDataContent.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
A bug in mid event callback was recently fixed. In order to populate the callback with case data, we need to pass the casereference in the case data content.
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
> ROC-5471 Add case reference to CaseDataContent

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseUserApiTest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseUserApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseUser.java
https://tools.hmcts.net/jira/browse/DIV-4632
> Expose case roles endpoint for the case+user

- README.md
- build.gradle
- scripts/create-role.sh
- scripts/idam-authenticate.sh
- scripts/import-definition.sh
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/BaseTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseAccessApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseEventsApiTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseUserApiTest.java
- src/functionalTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseEventsApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataClientAutoConfiguration.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseEventDetail.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseEventDetails.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/SignificantItem.java
- src/test/java/uk/gov/hmcts/reform/ccd/client/CaseEventsApiTest.java
- src/test/resources/application.yaml
- src/test/resources/caseEvents.json
Add case event apis
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```
> Add case event apis

- src/main/java/uk/gov/hmcts/reform/ccd/client/model/AboutToStartOrSubmitCallbackResponse.java
https://tools.hmcts.net/jira/browse/ROC-8482
Override claim status using  state field from callback handler
> Override claim status using  state field

- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
https://tools.hmcts.net/jira/browse/ROC-8858
MockBean behaviour for Feign Clients change since Spring Boot 2.2.7 Release
> MockBean behaviour for Feign Client since Spring Boot 2.2.7

- .github/workflows/gradle.yml
- .github/workflows/jitpack-build.yml
- README.md
- build.gradle
- Remove bintray config and workflow task
- Add Jitpack config and workflow
- Update readme with jitpack badge
> DTSPO-1792 - Add JitPack configuration and workflow 

- src/main/java/uk/gov/hmcts/reform/ccd/client/model/AboutToStartOrSubmitCallbackResponse.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CallbackRequest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseAssignmentUserRole.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseAssignmentUserRolesRequest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseDataContent.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseDocument.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseUser.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/Event.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/EventRequestData.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/SignificantItem.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/SubmittedCallbackResponse.java
Add @Jacksonized to all builders
> More jackson

- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CaseAssignmentApiTest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CaseAssignmentApi.java
Add more variations of the /case-users endpoint
> more case user endpoint variations

- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApiTest.java
- src/functionalTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
https://tools.hmcts.net/jira/browse/SSCS-10068
Added endpoint to feign
> SSCS-10068 Add supplementary data endpoint

- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApiTest.java
- src/functionalTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CaseResource.java
- src/test/java/uk/gov/hmcts/reform/ccd/client/CcdClientTest.java
- src/test/java/uk/gov/hmcts/reform/ccd/client/mock/CcdWireMock.java
https://tools.hmcts.net/jira/browse/HMAN-319
Add support (models etc) and tests for datastore V2 "Submit event for case" endpoint
> HMAN-319 - add V2 "Submit event for case" endpoint

- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/CategoriesAndDocuments.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/Category.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/model/Document.java
Added API to fetch Documents and Categories for a particular case reference
> Added API to fetch Category and Files for Case Reference

- jitpack.yml
Add jitpack config to fix build
> Add jitpack.yml

- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
https://tools.hmcts.net/jira/browse/SSCSCI-954
> Create an overloaded start event for caseworker to allow to pass ignore warning flag

- src/functionalTest/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApiTest.java
- src/main/java/uk/gov/hmcts/reform/ccd/client/CoreCaseDataApi.java
https://tools.hmcts.net/jira/browse/SSCSCI-954
> Added ignore warning request param for start event caseworker
